plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.26.0'
    implementation 'org.testng:testng:7.11.0'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'

    implementation 'net.datafaker:datafaker:2.5.2'

    implementation 'ch.qos.logback:logback-classic:1.5.18'
}

test {
    useTestNG()
}

tasks.register('qa', Test) {
    useTestNG() {
        suites 'src/test/resources/testng.xml'
    }
}

tasks.register('scope', Test) {
    useTestNG() {
        suites 'src/test/resources/scope.xml'
    }

    if (project.hasProperty('browser')) {
        systemProperty 'browser', "${browser}"
    }
}

tasks.register('qa_suites', Test) {
    useTestNG() {
        def suite = System.getProperty('suite', '')

        if (suite.equals('registration_login')) {
            suites 'src/test/resources/testng.xml'
        } else if (suite.equals('smoke_tests')) {
            suites 'src/test/resources/scope.xml'
        } else {
            suites 'src/test/resources/base.xml'
        }
    }

    if (project.hasProperty('browser')) {
        systemProperty 'browser', "${browser}"
    }
}

tasks.register('groups', Test) {
    useTestNG() {
        def groups = System.getProperty('groups', '')

        if (groups != null) {
            includeGroups groups
        }
        suites 'src/test/resources/base.xml'
    }
}

